AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  NetworkStackName:
    Description: "The name of the base networking stack."
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: esuranceDemo
Resources:
  esuranceEC2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: ami-a4c7edb2
      InstanceType: m4.large
      KeyName: jc-keypair
      SubnetId:
        Fn::ImportValue: !Sub "${NetworkStackName}-SubnetAId"
      SecurityGroupIds:
        - Fn::ImportValue: !Sub "${NetworkStackName}-SecurityGroupId"
